# Generated by Django 5.1.7 on 2025-03-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='taskpreference',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
