# Generated by Django 5.1.7 on 2025-03-15 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="excludes",
            field=models.ManyToManyField(blank=True, to="schedules.task"),
        ),
        migrations.AddField(
            model_name="task",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="schedules.service"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="schedules.task"
            ),
        ),
        migrations.AddField(
            model_name="taskpreference",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="schedules.task"
            ),
        ),
        migrations.AddField(
            model_name="taskpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskpreference",
            unique_together={("user", "task")},
        ),
    ]
