# Generated by Django 5.1.7 on 2025-03-24 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="created_by",
            new_name="user",
        ),
    ]
