# Generated by Django 5.1.7 on 2025-03-24 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_rename_created_by_schedule_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 24, 2, 29, 0, 101954, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 24, 2, 29, 0, 101964, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
