# Generated by Django 5.1.7 on 2025-03-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_assignment_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
