# Generated by Django 5.1.7 on 2025-03-24 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_alter_schedule_created_at_alter_schedule_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
