# Generated by Django 5.1.7 on 2025-06-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_schedule_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="draft",
        ),
    ]
